# .streamlit/config.toml
[theme]
primaryColor = "#6C63FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"  # Options: "sans serif", "serif", "monospace"
